package examenii_p2_diegoandino;

import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Menu extends javax.swing.JFrame {

    private ArrayList<Deporte> deportes = new ArrayList();
    private DefaultMutableTreeNode actualizar;

    public Menu() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_CrearPar = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jCB_Equipo2 = new javax.swing.JComboBox<>();
        jCB_Equipo1 = new javax.swing.JComboBox<>();
        jS_Punto2 = new javax.swing.JSpinner();
        jS_Punto1 = new javax.swing.JSpinner();
        cb_equipo3 = new javax.swing.JComboBox<>();
        jB_NuevoPartido = new javax.swing.JButton();
        jD_CrearEqui = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_TeamName = new javax.swing.JTextField();
        jB_CrearEquip = new javax.swing.JButton();
        jD_ListarEquip = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jL_Lista = new javax.swing.JList<>();
        jB_Partidas = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jT_PartidasJugadas = new javax.swing.JTable();
        jD_Tabla = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTB_Tabla = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        JPP_Menu = new javax.swing.JPopupMenu();
        MI_CrearDepo = new javax.swing.JMenuItem();
        JPP_CrearTorneo = new javax.swing.JPopupMenu();
        MI_CrearTorn = new javax.swing.JMenuItem();
        JDD_Torneos = new javax.swing.JPopupMenu();
        MI_CrearEquip = new javax.swing.JMenuItem();
        MI_CrearPart = new javax.swing.JMenuItem();
        MI_ListarPart = new javax.swing.JMenuItem();
        MI_TablaPosi = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Tree = new javax.swing.JTree();
        progressBar = new javax.swing.JProgressBar();
        jB_Cargar = new javax.swing.JButton();
        jB_Guardar = new javax.swing.JButton();
        jCB_Principal = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jD_CrearPar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCB_Equipo2.setBackground(new java.awt.Color(60, 63, 65));
        jCB_Equipo2.setForeground(new java.awt.Color(153, 153, 153));
        jCB_Equipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jCB_Equipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 100, -1));

        jCB_Equipo1.setBackground(new java.awt.Color(60, 63, 65));
        jCB_Equipo1.setForeground(new java.awt.Color(153, 153, 153));
        jCB_Equipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jCB_Equipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, -1));

        jS_Punto2.setModel(new javax.swing.SpinnerNumberModel());
        jPanel3.add(jS_Punto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jS_Punto1.setModel(new javax.swing.SpinnerNumberModel());
        jPanel3.add(jS_Punto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        cb_equipo3.setBackground(new java.awt.Color(255, 255, 255));
        cb_equipo3.setForeground(new java.awt.Color(0, 0, 0));
        cb_equipo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cb_equipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 100, -1));

        jB_NuevoPartido.setBackground(new java.awt.Color(153, 153, 153));
        jB_NuevoPartido.setForeground(new java.awt.Color(51, 51, 51));
        jB_NuevoPartido.setText("Nuevo partido");
        jB_NuevoPartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_NuevoPartidoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB_NuevoPartidoMouseEntered(evt);
            }
        });
        jB_NuevoPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_NuevoPartidoActionPerformed(evt);
            }
        });
        jPanel3.add(jB_NuevoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, 50));

        jD_CrearPar.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 120));

        jD_CrearEqui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jD_CrearEqui.setBackground(new java.awt.Color(255, 51, 51));
        jD_CrearEqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jD_CrearEquiMouseClicked(evt);
            }
        });
        jD_CrearEqui.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Crear equipo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel4.setText("Nombre:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        TF_TeamName.setBackground(new java.awt.Color(153, 153, 153));
        TF_TeamName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(TF_TeamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 200, -1));

        jB_CrearEquip.setBackground(new java.awt.Color(153, 153, 153));
        jB_CrearEquip.setForeground(new java.awt.Color(0, 0, 0));
        jB_CrearEquip.setText("crear");
        jB_CrearEquip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_CrearEquipMouseClicked(evt);
            }
        });
        jB_CrearEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CrearEquipActionPerformed(evt);
            }
        });
        jPanel2.add(jB_CrearEquip, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, 70));

        jD_CrearEqui.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 90));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Listado Equipos");

        jL_Lista.setBackground(new java.awt.Color(153, 153, 153));
        jL_Lista.setForeground(new java.awt.Color(0, 0, 0));
        jL_Lista.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jL_Lista);

        jB_Partidas.setBackground(new java.awt.Color(153, 153, 153));
        jB_Partidas.setForeground(new java.awt.Color(0, 0, 0));
        jB_Partidas.setText("Partidos jugados");
        jB_Partidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_PartidasMouseClicked(evt);
            }
        });

        jT_PartidasJugadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Partidas"
            }
        ));
        jScrollPane5.setViewportView(jT_PartidasJugadas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jB_Partidas)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(212, 212, 212))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jB_Partidas, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jD_ListarEquipLayout = new javax.swing.GroupLayout(jD_ListarEquip.getContentPane());
        jD_ListarEquip.getContentPane().setLayout(jD_ListarEquipLayout);
        jD_ListarEquipLayout.setHorizontalGroup(
            jD_ListarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jD_ListarEquipLayout.setVerticalGroup(
            jD_ListarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jD_Tabla.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTB_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Equipo", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTB_Tabla);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 350));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("---------LISTA---------");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jD_Tabla.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 410));

        MI_CrearDepo.setText("Crear Deporte");
        MI_CrearDepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_CrearDepoActionPerformed(evt);
            }
        });
        JPP_Menu.add(MI_CrearDepo);

        MI_CrearTorn.setText("Crear Torneo");
        MI_CrearTorn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_CrearTornActionPerformed(evt);
            }
        });
        JPP_CrearTorneo.add(MI_CrearTorn);

        MI_CrearEquip.setText("Crear Equipo");
        MI_CrearEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_CrearEquipActionPerformed(evt);
            }
        });
        JDD_Torneos.add(MI_CrearEquip);

        MI_CrearPart.setText("Crear Partido");
        MI_CrearPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_CrearPartActionPerformed(evt);
            }
        });
        JDD_Torneos.add(MI_CrearPart);

        MI_ListarPart.setText("Listar participantes");
        MI_ListarPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_ListarPartActionPerformed(evt);
            }
        });
        JDD_Torneos.add(MI_ListarPart);

        MI_TablaPosi.setText("Tabla de Posiciones");
        MI_TablaPosi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_TablaPosiActionPerformed(evt);
            }
        });
        JDD_Torneos.add(MI_TablaPosi);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jT_Tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_TreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_Tree);

        jB_Cargar.setText("Cargar");
        jB_Cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_CargarMouseClicked(evt);
            }
        });
        jB_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CargarActionPerformed(evt);
            }
        });

        jB_Guardar.setText("Guardar");
        jB_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_GuardarMouseClicked(evt);
            }
        });
        jB_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GuardarActionPerformed(evt);
            }
        });

        jCB_Principal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EXAMEN II");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Diego Andino - 12241176");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jB_Cargar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jB_Guardar))
                                    .addComponent(jCB_Principal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(76, 76, 76))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCB_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_TreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_TreeMouseClicked
        jT_Tree.setSelectionRow(jT_Tree.getClosestRowForLocation(evt.getX(), evt.getY()));
        if (SwingUtilities.isRightMouseButton(evt)) {
            actualizar = (DefaultMutableTreeNode) jT_Tree.getSelectionPath().getLastPathComponent();
            if (actualizar.getUserObject() instanceof Deporte) {
                JPP_CrearTorneo.show(jT_Tree, evt.getX(), evt.getY());
            } else if (actualizar.getUserObject() instanceof String) {
                JPP_Menu.show(jT_Tree, evt.getX(), evt.getY());
            } else {
                JDD_Torneos.show(jT_Tree, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jT_TreeMouseClicked

    private void jB_CargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_CargarMouseClicked
        JFileChooser jfc = new JFileChooser();
        int op = jfc.showSaveDialog(jB_Guardar);
        if (op == JFileChooser.APPROVE_OPTION) {
            try {
                File f = jfc.getSelectedFile();
                if (f.exists()) {
                    String[] path = f.getPath().split("\\.");
                    if (path[path.length - 1].equals("dmaf")) {
                        FileInputStream in = new FileInputStream(f);
                        ObjectInputStream input = new ObjectInputStream(in);
                        try {
                            Deporte deporte = (Deporte) input.readObject();
                            deportes.add(deporte);
                            llenarTree();
                        } catch (EOFException ex) {

                        }
                        in.close();
                        input.close();

                    } else {
                        JOptionPane.showMessageDialog(this, "File Not Supported");
                    }

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        UpdateComboBox();
    }//GEN-LAST:event_jB_CargarMouseClicked

    private void jB_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_GuardarMouseClicked
        JFileChooser jfc = new JFileChooser();
        int op = jfc.showSaveDialog(jB_Guardar);
        if (op == JFileChooser.APPROVE_OPTION) {
            try {
                File f = jfc.getSelectedFile();
                if (!f.exists()) {
                    f = new File(f.getPath() + ".dmaf");
                }
                String[] path = f.getPath().split("\\.");
                if (path[path.length - 1].equals("dmaf")) {
                    ProgressBar pb = new ProgressBar(progressBar, ((Deporte) jCB_Principal.getSelectedItem()));
                    pb.start();
                    FileOutputStream out = new FileOutputStream(f, false);
                    ObjectOutputStream output = new ObjectOutputStream(out);
                    output.writeObject(((Deporte) jCB_Principal.getSelectedItem()));
                    out.close();
                    output.close();
                } else {
                    JOptionPane.showMessageDialog(jfc, "Archivo no valido");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jB_GuardarMouseClicked

    private void jB_NuevoPartidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_NuevoPartidoMouseClicked
        Equipos team1 = (Equipos) jCB_Equipo1.getSelectedItem();
        Equipos team2 = (Equipos) jCB_Equipo2.getSelectedItem();

        if (team1.equals(team2)) {
            JOptionPane.showMessageDialog(jD_CrearPar, "No se puede jugar contra el mismo equipo");
        } else {
            Partido p = new Partido(int) jS_Punto1.getValue(), (int) jS_Punto2.getValue());
            p.setEquipos(new String[]{team1.getNombre(), team2.getNombre()});
            team1.setPuntos(team1.getPuntos() + ((int) jS_Punto1.getValue()));
            team2.setPuntos(team2.getPuntos() + ((int) jS_Punto2.getValue()));
            ((Torneo) actualizar.getUserObject()).getPartidos().add(p);
            ((Torneo) actualizar.getUserObject()).sortTeams();
            jD_CrearPar.dispose();
        }
    }//GEN-LAST:event_jB_NuevoPartidoMouseClicked

    private void jB_NuevoPartidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_NuevoPartidoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_NuevoPartidoMouseEntered

    private void jB_NuevoPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_NuevoPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_NuevoPartidoActionPerformed

    private void jB_CrearEquipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_CrearEquipMouseClicked

        ArrayList<Equipos> equipos = ((Torneo) actualizar.getUserObject()).getEquipos();
        String newName = TF_TeamName.getText();
        int validacion = 0;

        for (Equipos equipo : equipos) {
            if (newName.equals(equipo.getNombre())) {
                validacion++;
                break;
            }
        }

        if (validacion == 0) {
            equipos.add(new Equipos(newName, 0));
            ((Torneo) actualizar.getUserObject()).sortTeams();
            jD_CrearEqui.dispose();
        } else {
            JOptionPane.showMessageDialog(jD_CrearEqui, "Nombre repetido");
        }
    }//GEN-LAST:event_jB_CrearEquipMouseClicked

    private void jD_CrearEquiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jD_CrearEquiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jD_CrearEquiMouseClicked

    private void jB_PartidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_PartidasMouseClicked
        if (jL_Lista.getSelectedIndex() != -1) {
            DefaultListModel modelo = (DefaultListModel) jL_Lista.getModel();
            Equipos e = (Equipos) modelo.getElementAt(jL_Lista.getSelectedIndex());
            DefaultTableModel tabla = (DefaultTableModel) jT_PartidasJugadas.getModel();
            tabla.setRowCount(0);
            for (Partido p : ((Torneo) actualizar.getUserObject()).getPartidos()) {
                if (p.getEquipos()[0].equals(e.getNombre()) || p.getEquipos()[1].equalsIgnoreCase(e.getNombre())) {
                    tabla.addRow(new Object[]{p});
                }
            }

        }
    }//GEN-LAST:event_jB_PartidasMouseClicked

    private void MI_CrearDepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_CrearDepoActionPerformed
        crearDeporte();
    }//GEN-LAST:event_MI_CrearDepoActionPerformed

    private void MI_CrearTornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_CrearTornActionPerformed
        crearTorneo();
    }//GEN-LAST:event_MI_CrearTornActionPerformed

    private void MI_CrearEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_CrearEquipActionPerformed
        TF_TeamName.setText("");
        jD_CrearEqui.pack();
        jD_CrearEqui.setLocationRelativeTo(this);
        jD_CrearEqui.setVisible(true);
    }//GEN-LAST:event_MI_CrearEquipActionPerformed

    private void MI_CrearPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_CrearPartActionPerformed
        if (((Torneo) actualizar.getUserObject()).getEquipos().size() < 2) {
            JOptionPane.showMessageDialog(jT_Tree, "Debe tener al menos 2 equipos para esta opcion");
        } else {

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) jCB_Equipo1.getModel();
            modelo.removeAllElements();
            for (Equipos e : ((Torneo) actualizar.getUserObject()).getEquipos()) {
                modelo.addElement(e);
            }

            modelo = (DefaultComboBoxModel) jCB_Equipo2.getModel();
            modelo.removeAllElements();
            for (Equipos e : ((Torneo) actualizar.getUserObject()).getEquipos()) {
                modelo.addElement(e);
            }
            jS_Punto1.setValue(0);
            jS_Punto2.setValue(0);
            jD_CrearPar.pack();
            jD_CrearPar.setLocationRelativeTo(this);
            jD_CrearPar.setVisible(true);

        }
    }//GEN-LAST:event_MI_CrearPartActionPerformed

    private void MI_ListarPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_ListarPartActionPerformed
        DefaultTableModel tabla = (DefaultTableModel) jT_PartidasJugadas.getModel();
        tabla.setRowCount(0);
        DefaultListModel modelo = (DefaultListModel) jL_Lista.getModel();
        modelo.removeAllElements();
        for (Equipos e : ((Torneo) actualizar.getUserObject()).getEquipos()) {
            modelo.addElement(e);
        }
        jD_ListarEquip.pack();
        jD_ListarEquip.setLocationRelativeTo(null);
        jD_ListarEquip.setVisible(true);

    }//GEN-LAST:event_MI_ListarPartActionPerformed

    private void MI_TablaPosiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_TablaPosiActionPerformed
        jD_Tabla.pack();
        jD_Tabla.setLocationRelativeTo(this);
        DefaultTableModel modelo = (DefaultTableModel) jTB_Tabla.getModel();
        modelo.setRowCount(0);
        for (Equipos e : ((Torneo) actualizar.getUserObject()).getEquipos()) {
            modelo.addRow(new Object[]{e.getNombre(), e.getPuntos()});
        }
        jD_Tabla.setVisible(true);
    }//GEN-LAST:event_MI_TablaPosiActionPerformed

    private void jB_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GuardarActionPerformed
        JFileChooser jfc = new JFileChooser();
        int op = jfc.showSaveDialog(jB_Guardar);
        if (op == JFileChooser.APPROVE_OPTION) {
            try {
                File f = jfc.getSelectedFile();
                if (!f.exists()) {
                    f = new File(f.getPath() + ".dmaf");
                } 
                    String[] path = f.getPath().split("\\.");
                    if (path[path.length - 1].equals("dmaf")) {
                        ProgressBar pb = new ProgressBar(progressBar, ((Deporte) jCB_Principal.getSelectedItem()));
                        pb.start();
                        FileOutputStream out = new FileOutputStream(f, false);
                        ObjectOutputStream output = new ObjectOutputStream(out);
                        output.writeObject(((Deporte) jCB_Principal.getSelectedItem()));
                        out.close();
                        output.close();
                    }else{
                        JOptionPane.showMessageDialog(jfc, "Archivo no valido");
                    }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jB_GuardarActionPerformed

    private void jB_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CargarActionPerformed
        JFileChooser jfc = new JFileChooser();
        int op = jfc.showSaveDialog(jB_Guardar);
        if (op == JFileChooser.APPROVE_OPTION) {
            try {
                File f = jfc.getSelectedFile();
                if (f.exists()) {
                    String[] path = f.getPath().split("\\.");
                    if (path[path.length - 1].equals("dar")) {
                        FileInputStream in = new FileInputStream(f);
                        ObjectInputStream input = new ObjectInputStream(in);
                        try {
                            Deporte deporte = (Deporte) input.readObject();
                            deportes.add(deporte);
                            llenarTree();
                        } catch (EOFException ex) {

                        }
                        in.close();
                        input.close();

                    } else {
                        JOptionPane.showMessageDialog(this, "File Not Supported");
                    }

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        UpdateComboBox();
                                       
    }//GEN-LAST:event_jB_CargarActionPerformed

    private void jB_CrearEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CrearEquipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_CrearEquipActionPerformed

    public void llenarTree() {
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Torneos");
        DefaultTreeModel modelo = (DefaultTreeModel) jT_Tree.getModel();
        modelo.setRoot(raiz);
        for (int i = 1; i <= 5; i++) {
            if (i != 3) {
                String x = "Q" + Integer.toString(i);
                raiz.add(new DefaultMutableTreeNode(x));
            }

        }

        for (int i = 0; i < raiz.getChildCount(); i++) {
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) raiz.getChildAt(i);
            String nombre = (String) nodo.getUserObject();

            for (Deporte deporte : deportes) {
                DefaultMutableTreeNode sport = new DefaultMutableTreeNode(deporte);

                nodo.add(sport);
                for (Torneo t : deporte.getTorneos()) {
                    if (t.getPeriodo().equals((String) nodo.getUserObject())) {
                        sport.add(new DefaultMutableTreeNode(t));
                    }
                }
            }
        }
        modelo.reload();
    }
    
    public void UpdateComboBox() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jCB_Principal.getModel();
        modelo.removeAllElements();
        for (Deporte deporte : deportes) {
            modelo.addElement(deporte);
        }
    }
    
    public void crearTorneo() {
        DefaultMutableTreeNode padre = (DefaultMutableTreeNode) actualizar.getParent();

        ((Deporte) actualizar.getUserObject()).getTorneos().add(new Torneo(JOptionPane.showInputDialog("Ingrese nombre de torneo:"), (String) padre.getUserObject()));
        llenarTree();
    }
    
     public void crearDeporte() {
        String nombre = JOptionPane.showInputDialog("Ingrese nombre de deporte:");

        deportes.add(new Deporte(nombre));
        UpdateComboBox();
        llenarTree();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu JDD_Torneos;
    private javax.swing.JPopupMenu JPP_CrearTorneo;
    private javax.swing.JPopupMenu JPP_Menu;
    private javax.swing.JMenuItem MI_CrearDepo;
    private javax.swing.JMenuItem MI_CrearEquip;
    private javax.swing.JMenuItem MI_CrearPart;
    private javax.swing.JMenuItem MI_CrearTorn;
    private javax.swing.JMenuItem MI_ListarPart;
    private javax.swing.JMenuItem MI_TablaPosi;
    private javax.swing.JTextField TF_TeamName;
    private javax.swing.JComboBox<String> cb_equipo3;
    private javax.swing.JButton jB_Cargar;
    private javax.swing.JButton jB_CrearEquip;
    private javax.swing.JButton jB_Guardar;
    private javax.swing.JButton jB_NuevoPartido;
    private javax.swing.JButton jB_Partidas;
    private javax.swing.JComboBox<String> jCB_Equipo1;
    private javax.swing.JComboBox<String> jCB_Equipo2;
    private javax.swing.JComboBox<String> jCB_Principal;
    private javax.swing.JDialog jD_CrearEqui;
    private javax.swing.JDialog jD_CrearPar;
    private javax.swing.JDialog jD_ListarEquip;
    private javax.swing.JDialog jD_Tabla;
    private javax.swing.JList<String> jL_Lista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jS_Punto1;
    private javax.swing.JSpinner jS_Punto2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTB_Tabla;
    private javax.swing.JTable jT_PartidasJugadas;
    private javax.swing.JTree jT_Tree;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
